#!/usr/bin/env python3
"""Generate pkg/secretchat/wordlist.go.

The visual fingerprint needs exactly 2048 words so each carries 11 bits.

The list is generated rather than curated, for three reasons:

  * Every implementation — Go, TypeScript, Kotlin — can regenerate the
    identical list from this script, so no data file has to be vendored and
    kept in step across three languages.
  * Every entry is a pronounceable nonsense syllable, so nothing in the list
    is offensive, ambiguous, or unfortunate in some language we did not think
    about. A user reading a fingerprint aloud to a colleague should not have
    to.
  * The words are visually distinct at a glance, which is what makes a
    mismatch obvious rather than something you have to squint at.

Run: python3 scripts/gen-wordlist.py
"""

ONSETS = [
    "b", "d", "f", "g", "h", "j", "k", "l", "m", "n", "p", "r", "s", "t", "v", "z",
    "br", "dr", "fr", "gr", "kr", "pr", "tr", "bl", "fl", "gl", "kl", "pl",
    "sl", "st", "sp", "sk", "sn", "sw",
]
NUCLEI = ["a", "e", "i", "o", "u", "ai", "ee", "oo"]
CODAS = ["", "n", "r", "s", "t", "l", "k", "m"]

TARGET = 2048


def build() -> list[str]:
    seen, words = set(), []
    for onset in ONSETS:
        for nucleus in NUCLEI:
            for coda in CODAS:
                word = onset + nucleus + coda
                # Two-letter entries are too easy to mishear over a phone
                # call, which is exactly where this gets read aloud.
                if len(word) < 3 or word in seen:
                    continue
                seen.add(word)
                words.append(word)
    if len(words) < TARGET:
        raise SystemExit(f"only {len(words)} unique words; need {TARGET}")
    return words[:TARGET]


HEADER = '''package secretchat

// wordList is the 2048-entry vocabulary the visual fingerprint draws from.
//
// 2048 entries is exactly 11 bits per word, so five words carry 55 bits —
// enough that forging a matching pair is infeasible, short enough that people
// actually finish reading it aloud. A longer sequence nobody compares
// protects nothing.
//
// The words are generated, not curated: each is a pronounceable nonsense
// syllable, so the list is identical in every implementation without shipping
// a data file, and it contains no real word that could be offensive or
// ambiguous in some language.
//
// Generated by scripts/gen-wordlist.py — do not edit by hand.
var wordList = [...]string{
'''


def main() -> None:
    words = build()
    out = [HEADER]
    for i in range(0, len(words), 8):
        out.append("\t" + ", ".join(f'"{w}"' for w in words[i:i + 8]) + ",\n")
    out.append("}\n")

    with open("pkg/secretchat/wordlist.go", "w") as f:
        f.write("".join(out))
    print(f"wrote pkg/secretchat/wordlist.go with {len(words)} entries")


if __name__ == "__main__":
    main()
