#!/usr/bin/env bash
#
# Renders the platform ConfigMap from Terraform output.
#
# This exists so the manifests cannot drift from the infrastructure. Every
# value in the ConfigMap that describes *where something is* — the Kafka
# bootstrap address, the Redis endpoints, the Cloud SQL connection name — is
# produced by Terraform and copied here mechanically, rather than typed twice.
#
# Usage: ./scripts/render-env.sh ENV > deploy/k8s/overlays/ENV/platform-config.env

set -euo pipefail

ENV="${1:?usage: $0 ENV (dev|staging|prod)}"
TF_DIR="$(cd "$(dirname "$0")/../deploy/terraform" && pwd)"

cd "${TF_DIR}"

if ! terraform output -json workload_env >/dev/null 2>&1; then
  echo "no terraform output available." >&2
  echo "run: terraform init -backend-config=envs/${ENV}/backend.hcl" >&2
  exit 1
fi

terraform output -json workload_env | python3 -c '
import json, sys
data = json.load(sys.stdin)
print("# Generated by scripts/render-env.sh. Do not edit by hand:")
print("# every value here comes from terraform output workload_env.")
for k in sorted(data):
    print(f"{k}={data[k]}")
'
