-- 0001_init: accounts, devices, chats, membership.
--
-- Applied by the db-migrate Job (deploy/k8s/jobs/db-migrate.yaml) before any
-- new service version rolls out.
--
-- Migration discipline for a live system: every statement here is additive or
-- guarded. A column is never dropped in the same release that stops writing
-- it, because during a rolling deploy the old and new versions run at once.

BEGIN;

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
--
-- id is a snowflake generated by the application, not a bigserial. Two
-- reasons: it is assignable before the insert (so the caller can reference it
-- in the same transaction), and it carries a timestamp, which makes
-- "accounts created this week" a range scan instead of a sort.
CREATE TABLE IF NOT EXISTS users (
    id             bigint PRIMARY KEY,
    phone          text        NOT NULL,
    username       text,
    display_name   text        NOT NULL,
    about_text     text        NOT NULL DEFAULT '',
    avatar_object  text,
    lang_code      text        NOT NULL DEFAULT 'en',
    banned         boolean     NOT NULL DEFAULT false,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    deleted_at     timestamptz,

    CONSTRAINT users_phone_format CHECK (phone ~ '^(\+[1-9][0-9]{7,14}|deleted:[0-9]+)$'),
    CONSTRAINT users_display_name_length CHECK (char_length(display_name) BETWEEN 1 AND 64),
    CONSTRAINT users_about_length CHECK (char_length(about_text) <= 280)
);

-- Phone is unique among live accounts only. A deleted account's phone is
-- rewritten to 'deleted:<id>' so the number can be reused, which is what
-- makes account deletion actually free the identifier.
CREATE UNIQUE INDEX IF NOT EXISTS users_phone_key
    ON users (phone) WHERE deleted_at IS NULL;

-- Usernames are case-insensitive for uniqueness but case-preserving for
-- display, so "Ahmed" and "ahmed" cannot both exist.
CREATE UNIQUE INDEX IF NOT EXISTS users_username_key
    ON users (lower(username)) WHERE username IS NOT NULL AND deleted_at IS NULL;

-- Supports the prefix search on the "add contact" screen. text_pattern_ops is
-- required for LIKE 'prefix%' to use the index at all under a non-C collation.
CREATE INDEX IF NOT EXISTS users_username_prefix_idx
    ON users (lower(username) text_pattern_ops) WHERE username IS NOT NULL AND deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- devices — one row per authenticated session
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devices (
    id            bigint PRIMARY KEY,
    user_id       bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- The MTProto auth key identifier, hex-encoded. The key material itself
    -- lives only in Redis and is never written here.
    auth_key_id   text        NOT NULL,
    platform      text        NOT NULL DEFAULT 'unknown',
    app_version   text        NOT NULL DEFAULT '',
    device_model  text        NOT NULL DEFAULT '',
    push_token    text,
    last_ip       text        NOT NULL DEFAULT '',
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_seen_at  timestamptz NOT NULL DEFAULT now(),
    revoked_at    timestamptz,

    CONSTRAINT devices_platform_valid
        CHECK (platform IN ('android', 'ios', 'web', 'desktop', 'tcp', 'udp', 'ws', 'unknown'))
);

-- The auth key is the session's identity, so it is globally unique — including
-- across revoked rows, because reusing a revoked key must never resurrect it.
CREATE UNIQUE INDEX IF NOT EXISTS devices_auth_key_id_key ON devices (auth_key_id);

CREATE INDEX IF NOT EXISTS devices_user_active_idx
    ON devices (user_id, last_seen_at DESC) WHERE revoked_at IS NULL;

-- The push consumer's hot query: "give me every notifiable device for these
-- users". A partial index on exactly that predicate keeps it index-only.
CREATE INDEX IF NOT EXISTS devices_push_targets_idx
    ON devices (user_id) INCLUDE (id, push_token, platform)
    WHERE revoked_at IS NULL AND push_token IS NOT NULL;

-- ---------------------------------------------------------------------------
-- chats
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chats (
    id            bigint PRIMARY KEY,
    chat_type     text        NOT NULL,
    title         text        NOT NULL DEFAULT '',
    username      text,
    photo_object  text,
    description   text        NOT NULL DEFAULT '',
    created_by    bigint      NOT NULL REFERENCES users (id),
    member_count  integer     NOT NULL DEFAULT 0,
    -- The canonical "min:max" member pair for private chats. Unique, so two
    -- users can never end up with two parallel private conversations no
    -- matter how many devices tap "message" at once.
    pair_key      text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz,

    CONSTRAINT chats_type_valid CHECK (chat_type IN ('private', 'group', 'channel')),
    CONSTRAINT chats_member_count_sane CHECK (member_count >= 0),
    -- A private chat must have a pair key; a group or channel must not.
    CONSTRAINT chats_pair_key_matches_type CHECK (
        (chat_type = 'private' AND pair_key IS NOT NULL) OR
        (chat_type <> 'private' AND pair_key IS NULL)
    ),
    CONSTRAINT chats_title_required_for_groups CHECK (
        chat_type = 'private' OR char_length(title) BETWEEN 1 AND 128
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS chats_pair_key_key
    ON chats (pair_key) WHERE pair_key IS NOT NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS chats_username_key
    ON chats (lower(username)) WHERE username IS NOT NULL AND deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- chat_members
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_members (
    chat_id        bigint      NOT NULL REFERENCES chats (id) ON DELETE CASCADE,
    user_id        bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role           text        NOT NULL DEFAULT 'member',
    joined_at      timestamptz NOT NULL DEFAULT now(),
    -- The read pointer. Only ever moves forward (enforced in the query with
    -- GREATEST, not by a constraint, because a constraint would reject the
    -- out-of-order update rather than ignoring it).
    last_read_seq  bigint      NOT NULL DEFAULT 0,
    muted_until    timestamptz,
    pinned         boolean     NOT NULL DEFAULT false,
    archived       boolean     NOT NULL DEFAULT false,
    left_at        timestamptz,

    PRIMARY KEY (chat_id, user_id),
    CONSTRAINT chat_members_role_valid
        CHECK (role IN ('owner', 'admin', 'member', 'restricted')),
    CONSTRAINT chat_members_read_seq_sane CHECK (last_read_seq >= 0)
);

-- The chat-list query: every user's active memberships, newest first.
CREATE INDEX IF NOT EXISTS chat_members_user_idx
    ON chat_members (user_id) WHERE left_at IS NULL;

-- The fanout query: every active member of a chat.
CREATE INDEX IF NOT EXISTS chat_members_chat_idx
    ON chat_members (chat_id) WHERE left_at IS NULL;

-- The push consumer's mute check.
CREATE INDEX IF NOT EXISTS chat_members_muted_idx
    ON chat_members (chat_id, user_id) WHERE muted_until IS NOT NULL;

-- A chat has exactly one owner. A partial unique index expresses that
-- directly; a trigger would be the alternative and is far easier to get wrong.
CREATE UNIQUE INDEX IF NOT EXISTS chat_members_single_owner
    ON chat_members (chat_id) WHERE role = 'owner' AND left_at IS NULL;

-- ---------------------------------------------------------------------------
-- chat_sequences — the mirrored high-water mark
-- ---------------------------------------------------------------------------
--
-- Kept current by the persister. Its whole purpose is to make the chat list —
-- the first screen every client renders — a single Postgres query instead of
-- one Cassandra read per chat.
CREATE TABLE IF NOT EXISTS chat_sequences (
    chat_id    bigint PRIMARY KEY REFERENCES chats (id) ON DELETE CASCADE,
    max_seq    bigint      NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT chat_sequences_sane CHECK (max_seq >= 0)
);

-- Orders the chat list by recency without touching the messages themselves.
CREATE INDEX IF NOT EXISTS chat_sequences_updated_idx ON chat_sequences (updated_at DESC);

-- ---------------------------------------------------------------------------
-- otp_challenges
-- ---------------------------------------------------------------------------
--
-- Only the bcrypt hash of the code is stored, so a database leak does not hand
-- an attacker live login codes.
CREATE TABLE IF NOT EXISTS otp_challenges (
    id          text PRIMARY KEY,
    phone       text        NOT NULL,
    code_hash   text        NOT NULL,
    attempts    integer     NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),
    expires_at  timestamptz NOT NULL,
    consumed_at timestamptz,

    CONSTRAINT otp_attempts_sane CHECK (attempts >= 0)
);

CREATE INDEX IF NOT EXISTS otp_phone_idx ON otp_challenges (phone, created_at DESC);
-- Supports the purge CronJob.
CREATE INDEX IF NOT EXISTS otp_expiry_idx ON otp_challenges (expires_at);

-- ---------------------------------------------------------------------------
-- contacts
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contacts (
    owner_id   bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    user_id    bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    first_name text        NOT NULL DEFAULT '',
    last_name  text        NOT NULL DEFAULT '',
    added_at   timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (owner_id, user_id),
    CONSTRAINT contacts_not_self CHECK (owner_id <> user_id)
);

-- "Who has me in their contacts?" — needed to decide who sees presence.
CREATE INDEX IF NOT EXISTS contacts_reverse_idx ON contacts (user_id);

-- ---------------------------------------------------------------------------
-- blocklist
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS blocklist (
    owner_id   bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    blocked_id bigint      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (owner_id, blocked_id),
    CONSTRAINT blocklist_not_self CHECK (owner_id <> blocked_id)
);

CREATE INDEX IF NOT EXISTS blocklist_blocked_idx ON blocklist (blocked_id);

COMMIT;
